<?php // Newsletter Signup Checkbox
if (Mage::helper('space48_newslettersignup')->checkboxEnabled() && $this->notSubscribed()) { ?>
    <li class="fields">
        <div class="field">
            <label for="billing:newslettersignup">Sign Up for Newsletter</label>
            <div class="input-box">
                <input type="checkbox" name="billing[newslettersignup]" value="Yes"
                       title="Sign Up for Newsletter" id="billing:newslettersignup"
                    <?php echo (Mage::helper('space48_newslettersignup')->checkedByDefault()) ? ' checked="checked"' : '' ?> />
            </div>
        </div>
    </li>
<?php } // End of Newsletter Signup Checkbox ?>